from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .medicoCreateView import MedicoCreateView
from .pacienteCreateView import PacienteCreateView
from .historiaClinicaCreateView import HistoriaClinicaCreateView
from .enfermeroPacienteCreateView import EnfermeroPacienteCreateView
from .familiarCreateView import FamiliarCreateView
from .userCreateView import UserEditview