# Generated by Django 4.1.1 on 2022-09-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=20, verbose_name='user_type')),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido')),
                ('direccion', models.CharField(max_length=30, verbose_name='direccion')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnfermeroPaciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('citaDate', models.DateTimeField()),
                ('notas', models.CharField(max_length=100, verbose_name='notas')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.CharField(max_length=45, verbose_name='oximetria')),
                ('f_respiratoria', models.IntegerField(default=0)),
                ('f_cardiaca', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('presionArterial', models.IntegerField(default=0)),
                ('glicemias', models.IntegerField(default=0)),
                ('diagnostico', models.CharField(max_length=100, verbose_name='diagnostico')),
                ('sugerencia', models.CharField(max_length=100, verbose_name='sugerencia')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(max_length=50, verbose_name='especialidad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGeneral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=50, verbose_name='area')),
                ('auxiliar', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGeneral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enfermeroId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hospitalApp.enfermeropaciente')),
                ('hisCliId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hospitalApp.historiaclinica')),
                ('medicoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='hospitalApp.medico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='enfermeropaciente',
            name='auxiliarId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermeroPaciente', to='hospitalApp.usergeneral'),
        ),
    ]
